package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/jfgmesquita/terraform-provider-nextdns/internal/nextdns"
)

// Ensure SecurityResource satisfies the framework interfaces.
var _ resource.Resource = &SecurityResource{}
var _ resource.ResourceWithImportState = &SecurityResource{}

func NewSecurityResource() resource.Resource {
	return &SecurityResource{}
}

// SecurityResource manages the security settings of a NextDNS profile.
type SecurityResource struct {
	client *nextdns.Client
}

// SecurityResourceModel maps the resource schema to Go values.
type SecurityResourceModel struct {
	ProfileID                types.String `tfsdk:"profile_id"`
	ThreatIntelligenceFeeds  types.Bool   `tfsdk:"threat_intelligence_feeds"`
	AIThreatDetection        types.Bool   `tfsdk:"ai_threat_detection"`
	GoogleSafeBrowsing       types.Bool   `tfsdk:"google_safe_browsing"`
	Cryptojacking            types.Bool   `tfsdk:"cryptojacking"`
	DNSRebinding             types.Bool   `tfsdk:"dns_rebinding"`
	IDNHomographs            types.Bool   `tfsdk:"idn_homographs"`
	Typosquatting            types.Bool   `tfsdk:"typosquatting"`
	DGA                      types.Bool   `tfsdk:"dga"`
	NRD                      types.Bool   `tfsdk:"nrd"`
	NewlyActiveDomains       types.Bool   `tfsdk:"newly_active_domains"`
	FreeHostingDomains       types.Bool   `tfsdk:"free_hosting_domains"`
	DDNS                     types.Bool   `tfsdk:"ddns"`
	TunnelingEndpoints       types.Bool   `tfsdk:"tunneling_endpoints"`
	DataDropServices         types.Bool   `tfsdk:"data_drop_services"`
	ResidentialHosting       types.Bool   `tfsdk:"residential_hosting"`
	UntrustedCertificates    types.Bool   `tfsdk:"untrusted_certificates"`
	DNSPayloadDelivery       types.Bool   `tfsdk:"dns_payload_delivery"`
	DecentralizedWebGateways types.Bool   `tfsdk:"decentralized_web_gateways"`
	HighRiskTLDs             types.Bool   `tfsdk:"high_risk_tlds"`
	Parking                  types.Bool   `tfsdk:"parking"`
	CSAM                     types.Bool   `tfsdk:"csam"`
	TLDs                     types.Set    `tfsdk:"tlds"`
}

// securityToggles describes every on/off setting, by attribute name.
var securityToggles = map[string]string{
	"threat_intelligence_feeds":  "Block domains known to distribute malware, launch phishing attacks and host command-and-control servers using a blend of the most reputable threat intelligence feeds — all updated in real time.",
	"ai_threat_detection":        "Block millions of threats detected by NextDNS's AI technology — a proprietary AI engine designed from the ground up for DNS with hundreds of signals, terabytes of training data and real-time decision making. Includes IDN homographs, typosquatting, combosquatting, DGA domains, brand impersonation, credential harvesting, malware delivery, and decoy websites used to conceal malicious infrastructure.",
	"google_safe_browsing":       "Block malware and phishing domains using Google Safe Browsing — a technology that examines billions of URLs per day looking for unsafe websites. Unlike the version embedded in some browsers, this does not associate your public IP address with threats and does not allow bypassing the block.",
	"cryptojacking":              "Block cryptocurrency mining domains to help prevent cryptojacking — the unauthorized use of your devices to mine cryptocurrency.",
	"dns_rebinding":              "Block DNS responses containing local network addresses to help protect your devices from DNS rebinding attacks.",
	"idn_homographs":             "Block internationalized domain names (IDNs) that impersonate other domains using look-alike characters — e.g., replacing the Latin letter “e” with the Cyrillic letter “е”.",
	"typosquatting":              "Block domains registered by malicious actors that target users who incorrectly type a website address into their browser — e.g., gooogle.com instead of google.com.",
	"dga":                        "Block domains generated by Domain Generation Algorithms (DGA) and used by various families of malware as rendezvous points with their command-and-control servers.",
	"nrd":                        "Block domains registered less than 30 days ago. Those domains are known to be favored by threat actors to launch malicious campaigns.",
	"newly_active_domains":       "Block domains that are being accessed for the first time or have historically low activity. This prevents zero-day attacks and \"sleeper\" threats by requiring a proven footprint of legitimate usage before a domain is trusted, effectively neutralizing attempts to \"pre-warm\" malicious domains.",
	"free_hosting_domains":       "Block the default subdomains provided by free web hosting services (e.g., *.pages.dev, *.vercel.app, *.netlify.app). These \"Free Hosting Domains\" (FHDs) are heavily abused by attackers to host phishing sites and bypass reputation filters. This setting does not affect legitimate websites that use these providers behind a custom domain name.",
	"ddns":                       "Block Dynamic DNS (DDNS) hostnames. DDNS services let malicious actors quickly set up hostnames for free and without any validation or identity verification. While legit DDNS hostnames are rarely accessed in everyday use, their malicious counterparts are heavily used in phishing campaigns. If you are using DDNS, note that this setting will not block the DDNS services' own website or their update API.",
	"tunneling_endpoints":        "Block services that tunnel local traffic to the public internet (e.g., ngrok, Cloudflare Tunnel). These tools are frequently used by attackers to bypass firewalls and host phishing pages on random subdomains while concealing their underlying infrastructure.",
	"data_drop_services":         "Block access to dedicated services for sharing text, files, and JSON/configuration data or collecting incoming data, including webhook requests, DNS queries, and email. This includes legitimate uses of these services.",
	"residential_hosting":        "Block domains that resolve to residential IP ranges (ISPs) rather than commercial data centers. Legitimate web services are rarely hosted on consumer connections, while botnet C2 servers and phishing proxies frequently run on compromised home routers.",
	"untrusted_certificates":     "Block domains that serve SSL/TLS certificates signed by untrusted or unknown Certificate Authorities (e.g., self-signed). While legitimate websites almost exclusively use trusted certificates, nearly 60% of commodity malware Command-and-Control (C2) servers rely on self-signed certificates or certificates issued by untrusted authorities to encrypt their traffic without leaving a paper trail.",
	"dns_payload_delivery":       "Limit the data DNS responses can carry to disrupt the delivery of hidden commands or payloads to your devices, while preserving everyday browsing.",
	"decentralized_web_gateways": "Block public gateways that bridge the decentralized web (e.g., IPFS) to standard browsers. Attackers heavily abuse these services to host \"immutable\" phishing pages and malware, allowing threats to persist by evading traditional takedowns and reputation filters.",
	"high_risk_tlds":             "Automatically block Top-Level Domains (TLDs) that are statistically dominated by malicious activity — e.g., .zip, .mov, .top. The list is updated in real time based on global abuse reputation data, protecting you from vast networks of cheap, disposable domains used for phishing and spam without requiring manual configuration.",
	"parking":                    "Block parked domains: single-page websites often laden with ads and devoid of any value. Parked domain monetization can expose visitors to scams, phishing pages, and malicious downloads through advertising networks and redirects.",
	"csam":                       "Block domains hosting child sexual abuse material with the help of Project Arachnid, operated by the Canadian Centre for Child Protection. No information is transmitted back to Project Arachnid when a domain is blocked.",
}

// togglePair links one Terraform attribute to its field in the API struct.
type togglePair struct {
	tf  *types.Bool
	api *bool
}

func securityTogglePairs(m *SecurityResourceModel, s *nextdns.Security) []togglePair {
	return []togglePair{
		{&m.ThreatIntelligenceFeeds, &s.ThreatIntelligenceFeeds},
		{&m.AIThreatDetection, &s.AIThreatDetection},
		{&m.GoogleSafeBrowsing, &s.GoogleSafeBrowsing},
		{&m.Cryptojacking, &s.Cryptojacking},
		{&m.DNSRebinding, &s.DNSRebinding},
		{&m.IDNHomographs, &s.IDNHomographs},
		{&m.Typosquatting, &s.Typosquatting},
		{&m.DGA, &s.DGA},
		{&m.NRD, &s.NRD},
		{&m.NewlyActiveDomains, &s.NewlyActiveDomains},
		{&m.FreeHostingDomains, &s.FreeHostingDomains},
		{&m.DDNS, &s.DDNS},
		{&m.TunnelingEndpoints, &s.TunnelingEndpoints},
		{&m.DataDropServices, &s.DataDropServices},
		{&m.ResidentialHosting, &s.ResidentialHosting},
		{&m.UntrustedCertificates, &s.UntrustedCertificates},
		{&m.DNSPayloadDelivery, &s.DNSPayloadDelivery},
		{&m.DecentralizedWebGateways, &s.DecentralizedWebGateways},
		{&m.HighRiskTLDs, &s.HighRiskTLDs},
		{&m.Parking, &s.Parking},
		{&m.CSAM, &s.CSAM},
	}
}

func (r *SecurityResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_security"
}

func (r *SecurityResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	attributes := map[string]schema.Attribute{
		"profile_id": schema.StringAttribute{
			MarkdownDescription: "ID of the profile these settings belong to.",
			Required:            true,
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
		},
		"tlds": schema.SetAttribute{
			MarkdownDescription: "Block all domains and subdomains belonging to specific top-level domains (TLDs). Values are TLDs without the dot, for example `[\"zip\", \"mov\"]`.",
			ElementType:         types.StringType,
			Optional:            true,
			Computed:            true,
			Default:             setdefault.StaticValue(emptyStringSet()),
		},
	}
	for name, description := range securityToggles {
		attributes[name] = schema.BoolAttribute{
			MarkdownDescription: description + " Defaults to `false`.",
			Optional:            true,
			Computed:            true,
			Default:             booldefault.StaticBool(false),
		}
	}

	resp.Schema = schema.Schema{
		MarkdownDescription: "The security settings of a NextDNS profile.\n\n" +
			"This resource manages all security settings: any setting left out of the configuration is turned off.\n\n" +
			"Removing this resource from the configuration, or destroying it, does not change any settings in NextDNS: " +
			"Terraform only stops managing them. To turn protections off, set them to `false` and apply.\n\n" +
			profilePartNotes("nextdns_security"),
		Attributes: attributes,
	}
}

func (r *SecurityResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*nextdns.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *nextdns.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *SecurityResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	// The security settings always exist, so creating means updating them.
	var data SecurityResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(r.update(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *SecurityResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data SecurityResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	security, err := r.client.GetSecurity(ctx, data.ProfileID.ValueString())
	if nextdns.IsNotFound(err) {
		// The profile was deleted outside Terraform.
		resp.State.RemoveResource(ctx)
		return
	}
	if err != nil {
		resp.Diagnostics.AddError("Error reading NextDNS security settings", err.Error())
		return
	}

	for _, p := range securityTogglePairs(&data, security) {
		*p.tf = types.BoolValue(*p.api)
	}

	tlds, diags := listItemsToSet(ctx, security.TLDs)
	resp.Diagnostics.Append(diags...)
	data.TLDs = tlds

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *SecurityResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data SecurityResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(r.update(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// update sends every setting in data to NextDNS.
func (r *SecurityResource) update(ctx context.Context, data *SecurityResourceModel) diag.Diagnostics {
	security := &nextdns.Security{}
	for _, p := range securityTogglePairs(data, security) {
		*p.api = p.tf.ValueBool()
	}

	tlds, diags := setToListItems(ctx, data.TLDs)
	if diags.HasError() {
		return diags
	}
	security.TLDs = tlds

	if err := r.client.UpdateSecurity(ctx, data.ProfileID.ValueString(), security); err != nil {
		diags.AddError("Error updating NextDNS security settings", err.Error())
	}
	return diags
}

func (r *SecurityResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// Intentionally empty: the security settings cannot be deleted, and
	// resetting them would silently turn protections off. Terraform removes
	// the resource from the state after this returns.
}

func (r *SecurityResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("profile_id"), req, resp)
}
